title: "مكتبة رمضان"
description: A resources library with summaries and interactive content for islamic religious studies.
theme: just-the-docs
base: ""
url: https://fatma-meawad.github.io/ramadan-library

# Enable custom styles
just_the_docs:
  custom_css: "assets/css/custom.css"

search_enabled: true
search.heading_level: 2  # Index h1, h2, and h3 headers
search.tokenizer_separator: /[\s\-/،؟؛.،]+/ 
mermaid:
  version: "11.1.0"

callouts:
  note:
    color: blue

  warning:
    color: red

  info:
    color: green