title: "مكتبة رمضان"
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

# Enable custom styles
just_the_docs:
  custom_css: "assets/css/custom.css"
